version: '3.8'

services:
  # --- НАШ БОТ ---
  bot:
    build: .
    container_name: parus_bot
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - MINIO_ENDPOINT=minio:9000
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - db
      - minio
      - ollama
    networks:
      - parus_net

  # --- БАЗА ДАННЫХ (с pgvector) ---
  db:
    image: pgvector/pgvector:pg16
    container_name: parus_db
    restart: always
    ports:
      # Внешний порт 5433 (чтобы не мешать локальному Postgres), внутренний 5432
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Данные базы будут лежать в папке pg_data в корне проекта
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - parus_net

  # --- ФАЙЛОВОЕ ХРАНИЛИЩЕ ---
  minio:
    image: minio/minio:latest
    container_name: parus_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./minio_data:/data
    networks:
      - parus_net

  # --- НЕЙРОСЕТЬ ---
  ollama:
    image: ollama/ollama:latest
    container_name: parus_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - parus_net
    environment:
      - OLLAMA_KEEP_ALIVE=24h

networks:
  parus_net:
    driver: bridge