version: '3.8'

services:
  bot:
    build: .
    container_name: parus_bot
    restart: always
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=minio:9000
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_URL=postgresql+asyncpg://postgres:${DATABASE_PASSWORD}@host.docker.internal:5432/parus_db
    volumes:
      - .:/app
      - /app/venv
    depends_on:
      - minio
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    networks:
      - parus_net

  minio:
    image: minio/minio:latest
    container_name: parus_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./minio_data:/data
    networks:
      - parus_net

  ollama:
    image: ollama/ollama:latest
    container_name: parus_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - parus_net
    environment:
      - OLLAMA_KEEP_ALIVE=24h

networks:
  parus_net:
    driver: bridge